---
# tasks file for docker
- name: Install Docker from script
  shell:
    cmd: curl https://get.docker.com | bash

- name: Append user to Docker group
  user:
    name: epica
    groups: docker
    append: yes